import type { Card } from '../tarot';

/**
 * Celestia Arcana Custom Tarot Deck
 * Original designs created exclusively for Celestia Arcana
 * All 78 cards with custom artwork and image paths
 */
export const celestiaArcanaCards: Card[] = [
  // MAJOR ARCANA (0-21)
  {
    id: 'ca-0',
    name: 'The Fool',
    upright: 'New beginnings, taking risks, innocence, spontaneity, faith in the journey',
    reversed: 'Recklessness, naivety, lack of planning, hesitation, fear of the unknown',
    image: '/cards/The_Fool.webp',
  },
  {
    id: 'ca-1',
    name: 'The Magician',
    upright: 'Manifestation, resourcefulness, power, inspired action, personal power',
    reversed: 'Manipulation, poor planning, untapped potential, lack of concentration',
    image: '/cards/The_Magician.webp',
  },
  {
    id: 'ca-2',
    name: 'The High Priestess',
    upright: 'Intuition, sacred knowledge, divine feminine, the subconscious, mystery',
    reversed: 'Secrets, disconnection from intuition, superficiality, hidden agendas',
    image: '/cards/The_High_Priestess.webp',
  },
  {
    id: 'ca-3',
    name: 'The Empress',
    upright: 'Femininity, beauty, abundance, nature, sensuality, creativity, nurturing',
    reversed: 'Self-doubt, lack of growth, insecurity, dependence on others',
    image: '/cards/The_Empress.webp',
  },
  {
    id: 'ca-4',
    name: 'The Emperor',
    upright: 'Authority, establishment, structure, control, leadership, stability',
    reversed: 'Domination, excessive control, lack of discipline, immaturity',
    image: '/cards/The_Emperor.webp',
  },
  {
    id: 'ca-5',
    name: 'The Hierophant',
    upright: 'Tradition, conformity, morality, ethics, education, spiritual guidance',
    reversed: 'Rebellion, subversion, unorthodoxy, personal beliefs, breaking free',
    image: '/cards/The_Hierophant.webp',
  },
  {
    id: 'ca-6',
    name: 'The Lovers',
    upright: 'Relationships, choices, alignment, values, connection, harmony, love',
    reversed: 'Misalignment, conflict, detachment, misunderstanding, separation',
    image: '/cards/The_Lovers.webp',
  },
  {
    id: 'ca-7',
    name: 'The Chariot',
    upright: 'Control, willpower, determination, self-discipline, ambition',
    reversed: 'Self-doubt, lack of direction, aggression, lack of control',
    image: '/cards/The_Chariot.webp',
  },
  {
    id: 'ca-8',
    name: 'Strength',
    upright: 'Inner strength, courage, patience, control, compassion',
    reversed: 'Self-doubt, weakness, insecurity, low energy, self-sabotage',
    image: '/cards/Strength.webp',
  },
  {
    id: 'ca-9',
    name: 'The Hermit',
    upright: 'Soul searching, introspection, inner guidance, contemplation',
    reversed: 'Isolation, loneliness, withdrawal, lost, disconnected',
    image: '/cards/The_Hermit.webp',
  },
  {
    id: 'ca-10',
    name: 'Wheel of Fortune',
    upright: 'Good luck, karma, life cycles, destiny, turning point',
    reversed: 'Bad luck, resistance to change, breaking cycles, bad timing',
    image: '/cards/Wheel_of_Fortune.webp',
  },
  {
    id: 'ca-11',
    name: 'Justice',
    upright: 'Justice, fairness, truth, cause and effect, accountability',
    reversed: 'Injustice, bias, unfairness, lack of accountability',
    image: '/cards/Justice.webp',
  },
  {
    id: 'ca-12',
    name: 'The Hanged Man',
    upright: 'Suspension, restriction, letting go, pause, new perspective',
    reversed: 'Avoidance, stalling, resistance, indecision',
    image: '/cards/The_Hanged_Man.webp',
  },
  {
    id: 'ca-13',
    name: 'Death',
    upright: 'Transformation, endings, beginnings, change, cycles',
    reversed: 'Resistance to change, stagnation, decay',
    image: '/cards/Death.webp',
  },
  {
    id: 'ca-14',
    name: 'Temperance',
    upright: 'Balance, moderation, patience, finding meaning, harmony',
    reversed: 'Imbalance, excess, lack of patience, extremes',
    image: '/cards/Temperance.webp',
  },
  {
    id: 'ca-15',
    name: 'The Devil',
    upright: 'Bondage, materialism, playfulness, detachment, sexuality',
    reversed: 'Detachment, overcoming adversity, breaking free, reclaiming power',
    image: '/cards/The_Devil.webp',
  },
  {
    id: 'ca-16',
    name: 'The Tower',
    upright: 'Sudden change, upheaval, chaos, revelation, awakening',
    reversed: 'Averted disaster, delayed change, fear of change, stagnation',
    image: '/cards/The_Tower.webp',
  },
  {
    id: 'ca-17',
    name: 'The Star',
    upright: 'Hope, faith, purpose, renewal, spirituality, clarity, inspiration',
    reversed: 'Despair, lack of faith, disconnection, lost direction, hopelessness',
    image: '/cards/The_Star.webp',
  },
  {
    id: 'ca-18',
    name: 'The Moon',
    upright: 'Illusion, fear, anxiety, subconscious, intuition, uncertainty',
    reversed: 'Clarity, release of fear, growing awareness, truth revealed',
    image: '/cards/The_Moon.webp',
  },
  {
    id: 'ca-19',
    name: 'The Sun',
    upright: 'Success, vitality, joy, warmth, illumination, positivity',
    reversed: 'Sadness, lack of clarity, depression, negativity, temporary setback',
    image: '/cards/The_Sun.webp',
  },
  {
    id: 'ca-20',
    name: 'Judgement',
    upright: 'Reckoning, awakening, renewal, reckoning, inner calling',
    reversed: 'Self-doubt, harsh self-criticism, doubt, an inner calling',
    image: '/cards/Judgement.webp',
  },
  {
    id: 'ca-21',
    name: 'The World',
    upright: 'Completion, accomplishment, fulfillment, wholeness, fulfillment',
    reversed: 'Incompleteness, lack of closure, seeking, lack of closure',
    image: '/cards/The_World.webp',
  },

  // SUIT OF FLAMES (Fire / Wands) (22-35)
  {
    id: 'ca-22',
    name: 'Ace of Flames',
    upright: 'Inspiration, new opportunities, growth, potential, new beginnings',
    reversed: 'Lack of energy, lack of growth, stagnation, lack of direction',
    image: '/cards/Ace_of_Flames.webp',
  },
  {
    id: 'ca-23',
    name: 'Two of Flames',
    upright: 'Partnership, planning, decision-making, balance, unity',
    reversed: 'Imbalance, conflict, indecision, lack of planning',
    image: '/cards/Two_of_Flames.webp',
  },
  {
    id: 'ca-24',
    name: 'Three of Flames',
    upright: 'Collaboration, teamwork, communication, growth, expansion',
    reversed: 'Conflict, miscommunication, lack of teamwork, delays',
    image: '/cards/Three_of_Flames.webp',
  },
  {
    id: 'ca-25',
    name: 'Four of Flames',
    upright: 'Celebration, joy, harmony, community, gathering',
    reversed: 'Conflict, isolation, lack of celebration, boredom',
    image: '/cards/Four_of_Flames.webp',
  },
  {
    id: 'ca-26',
    name: 'Five of Flames',
    upright: 'Conflict, competition, tension, struggle, challenge',
    reversed: 'Resolution, harmony, peace, agreement, compromise',
    image: '/cards/Five_of_Flames.webp',
  },
  {
    id: 'ca-27',
    name: 'Six of Flames',
    upright: 'Success, victory, achievement, recognition, progress',
    reversed: 'Failure, setback, lack of recognition, stagnation',
    image: '/cards/Six_of_Flames.webp',
  },
  {
    id: 'ca-28',
    name: 'Seven of Flames',
    upright: 'Courage, determination, perseverance, defense, protection',
    reversed: 'Weakness, cowardice, lack of determination, vulnerability',
    image: '/cards/Seven_of_Flames.webp',
  },
  {
    id: 'ca-29',
    name: 'Eight of Flames',
    upright: 'Speed, movement, progress, action, energy',
    reversed: 'Delays, stagnation, lack of progress, sluggishness',
    image: '/cards/Eight_of_Flames.webp',
  },
  {
    id: 'ca-30',
    name: 'Nine of Flames',
    upright: 'Resilience, strength, endurance, perseverance, determination',
    reversed: 'Exhaustion, burnout, weakness, giving up',
    image: '/cards/Nine_of_Flames.webp',
  },
  {
    id: 'ca-31',
    name: 'Ten of Flames',
    upright: 'Burden, responsibility, hard work, completion, success',
    reversed: 'Overwhelm, stress, burden, lack of support',
    image: '/cards/Ten_of_Flames.webp',
  },
  {
    id: 'ca-32',
    name: 'Page of Flames',
    upright: 'Enthusiasm, curiosity, exploration, discovery, adventure',
    reversed: 'Lack of direction, immaturity, lack of enthusiasm',
    image: '/cards/Page_of_Flames.webp',
  },
  {
    id: 'ca-33',
    name: 'Knight of Flames',
    upright: 'Passion, energy, action, adventure, impulsiveness',
    reversed: 'Recklessness, lack of direction, aggression, impatience',
    image: '/cards/Knight_of_Flames.webp',
  },
  {
    id: 'ca-34',
    name: 'Queen of Flames',
    upright: 'Confidence, independence, determination, passion, creativity',
    reversed: 'Insecurity, lack of confidence, lack of independence',
    image: '/cards/Queen_of_Flames.webp',
  },
  {
    id: 'ca-35',
    name: 'King of Flames',
    upright: 'Leadership, authority, vision, entrepreneurship, passion',
    reversed: 'Lack of leadership, lack of vision, aggression, domination',
    image: '/cards/King_of_Flames.webp',
  },

  // SUIT OF TIDES (Water / Cups) (36-49)
  {
    id: 'ca-36',
    name: 'Ace of Tides',
    upright: 'New feelings, relationships, creativity, joy, love',
    reversed: 'Blocked emotions, lack of creativity, emotional turmoil',
    image: '/cards/Ace_of_Tide.webp',
  },
  {
    id: 'ca-37',
    name: 'Two of Tides',
    upright: 'Partnership, connection, intimacy, unity, balance',
    reversed: 'Disconnection, conflict, imbalance, separation',
    image: '/cards/Two_of_Tides.webp',
  },
  {
    id: 'ca-38',
    name: 'Three of Tides',
    upright: 'Celebration, joy, friendship, community, gathering',
    reversed: 'Loneliness, isolation, lack of celebration, sorrow',
    image: '/cards/Three_of_Tides.webp',
  },
  {
    id: 'ca-39',
    name: 'Four of Tides',
    upright: 'Apathy, contemplation, meditation, rest, withdrawal',
    reversed: 'Engagement, action, movement, participation',
    image: '/cards/Four_of_Tides.webp',
  },
  {
    id: 'ca-40',
    name: 'Five of Tides',
    upright: 'Loss, grief, sorrow, sadness, disappointment',
    reversed: 'Recovery, healing, forgiveness, moving forward',
    image: '/cards/Five_of_Tides.webp',
  },
  {
    id: 'ca-41',
    name: 'Six of Tides',
    upright: 'Nostalgia, memories, childhood, innocence, joy',
    reversed: 'Living in the past, lack of progress, stagnation',
    image: '/cards/Six_of_Tides.webp',
  },
  {
    id: 'ca-42',
    name: 'Seven of Tides',
    upright: 'Illusion, fantasy, wishful thinking, choices, opportunities',
    reversed: 'Clarity, reality, truth, decision-making',
    image: '/cards/Seven_of_Tides.webp',
  },
  {
    id: 'ca-43',
    name: 'Eight of Tides',
    upright: 'Abandonment, walking away, leaving, moving on, transition',
    reversed: 'Staying, commitment, engagement, connection',
    image: '/cards/Eight_of_Tides.webp',
  },
  {
    id: 'ca-44',
    name: 'Nine of Tides',
    upright: 'Satisfaction, contentment, fulfillment, abundance, wishes',
    reversed: 'Lack of satisfaction, dissatisfaction, unfulfilled wishes',
    image: '/cards/Nine_of_Tides.webp',
  },
  {
    id: 'ca-45',
    name: 'Ten of Tides',
    upright: 'Family, harmony, happiness, home, unity',
    reversed: 'Conflict, disharmony, family issues, separation',
    image: '/cards/Ten_of_Tides.webp',
  },
  {
    id: 'ca-46',
    name: 'Page of Tides',
    upright: 'Curiosity, creativity, imagination, sensitivity, intuition',
    reversed: 'Lack of creativity, lack of sensitivity, immaturity',
    image: '/cards/Page_of_Tides.webp',
  },
  {
    id: 'ca-47',
    name: 'Knight of Tides',
    upright: 'Romance, charm, grace, imagination, sensitivity',
    reversed: 'Moodiness, insecurity, lack of direction, immaturity',
    image: '/cards/Knight_of_Tides.webp',
  },
  {
    id: 'ca-48',
    name: 'Queen of Tides',
    upright: 'Compassion, creativity, intuition, nurturing, emotional',
    reversed: 'Insecurity, lack of compassion, emotional instability',
    image: '/cards/Queen_of_Tides.webp',
  },
  {
    id: 'ca-49',
    name: 'King of Tides',
    upright: 'Emotional maturity, wisdom, compassion, leadership, calm',
    reversed: 'Emotional instability, lack of wisdom, moodiness',
    image: '/cards/King_of_Tides.webp',
  },

  // SUIT OF STONES (Earth / Pentacles) (50-63)
  {
    id: 'ca-50',
    name: 'Ace of Stones',
    upright: 'Prosperity, abundance, new opportunity, manifestation, wealth',
    reversed: 'Lack of abundance, missed opportunity, poverty, loss',
    image: '/cards/Ace_of_Stones.webp',
  },
  {
    id: 'ca-51',
    name: 'Two of Stones',
    upright: 'Balance, adaptability, time management, resourcefulness, flexibility',
    reversed: 'Imbalance, lack of adaptability, poor time management',
    image: '/cards/Two_of_Stones.webp',
  },
  {
    id: 'ca-52',
    name: 'Three of Stones',
    upright: 'Teamwork, collaboration, learning, growth, skill development',
    reversed: 'Lack of teamwork, lack of collaboration, lack of growth',
    image: '/cards/Three_of_Stones.webp',
  },
  {
    id: 'ca-53',
    name: 'Four of Stones',
    upright: 'Security, stability, protection, conservation, grounding',
    reversed: 'Insecurity, instability, lack of protection, loss',
    image: '/cards/Four_of_Stones.webp',
  },
  {
    id: 'ca-54',
    name: 'Five of Stones',
    upright: 'Hardship, struggle, poverty, loss, difficulty',
    reversed: 'Recovery, improvement, overcoming hardship, abundance',
    image: '/cards/Five_of_Stones.webp',
  },
  {
    id: 'ca-55',
    name: 'Six of Stones',
    upright: 'Generosity, charity, sharing, community, gratitude',
    reversed: 'Selfishness, lack of generosity, greed, stinginess',
    image: '/cards/Six_of_Stones.webp',
  },
  {
    id: 'ca-56',
    name: 'Seven of Stones',
    upright: 'Perseverance, patience, growth, investment, reward',
    reversed: 'Lack of patience, lack of growth, impatience, lack of reward',
    image: '/cards/Seven_of_Stones.webp',
  },
  {
    id: 'ca-57',
    name: 'Eight of Stones',
    upright: 'Skill, craftsmanship, mastery, learning, dedication',
    reversed: 'Lack of skill, lack of mastery, lack of dedication',
    image: '/cards/Eight_of_Stones.webp',
  },
  {
    id: 'ca-58',
    name: 'Nine of Stones',
    upright: 'Abundance, luxury, comfort, security, self-sufficiency',
    reversed: 'Lack of abundance, insecurity, lack of comfort',
    image: '/cards/Nine_of_Stones.webp',
  },
  {
    id: 'ca-59',
    name: 'Ten of Stones',
    upright: 'Wealth, family, legacy, inheritance, stability',
    reversed: 'Loss, lack of family support, instability, debt',
    image: '/cards/Ten_of_Stones.webp',
  },
  {
    id: 'ca-60',
    name: 'Page of Stones',
    upright: 'Curiosity, learning, study, practicality, reliability',
    reversed: 'Lack of curiosity, lack of learning, immaturity',
    image: '/cards/Page_of_Stones.webp',
  },
  {
    id: 'ca-61',
    name: 'Knight of Stones',
    upright: 'Reliability, responsibility, hard work, dedication, loyalty',
    reversed: 'Unreliability, lack of responsibility, laziness',
    image: '/cards/Knight_of_Stones.webp',
  },
  {
    id: 'ca-62',
    name: 'Queen of Stones',
    upright: 'Practicality, nurturing, abundance, security, generosity',
    reversed: 'Lack of practicality, lack of nurturing, insecurity',
    image: '/cards/Queen_of_Stones.webp',
  },
  {
    id: 'ca-63',
    name: 'King of Stones',
    upright: 'Abundance, prosperity, leadership, security, reliability',
    reversed: 'Lack of abundance, lack of leadership, unreliability',
    image: '/cards/King_of_Stones.webp',
  },

  // SUIT OF WINDS (Air / Swords) (64-77)
  {
    id: 'ca-64',
    name: 'Ace of Winds',
    upright: 'Clarity, truth, new ideas, communication, breakthrough',
    reversed: 'Confusion, lack of clarity, miscommunication, deception',
    image: '/cards/Ace_of_Winds.webp',
  },
  {
    id: 'ca-65',
    name: 'Two of Winds',
    upright: 'Indecision, stalemate, difficult choice, balance, truce',
    reversed: 'Decision-making, clarity, moving forward, resolution',
    image: '/cards/Two_of_Winds.webp',
  },
  {
    id: 'ca-66',
    name: 'Three of Winds',
    upright: 'Heartbreak, sorrow, grief, pain, separation',
    reversed: 'Healing, forgiveness, moving forward, recovery',
    image: '/cards/Three_of_Winds.webp',
  },
  {
    id: 'ca-67',
    name: 'Four of Winds',
    upright: 'Rest, recovery, meditation, contemplation, peace',
    reversed: 'Restlessness, anxiety, lack of peace, disturbance',
    image: '/cards/Four_of_Winds.webp',
  },
  {
    id: 'ca-68',
    name: 'Five of Winds',
    upright: 'Conflict, tension, struggle, competition, defeat',
    reversed: 'Resolution, peace, harmony, agreement, victory',
    image: '/cards/Five_of_Winds.webp',
  },
  {
    id: 'ca-69',
    name: 'Six of Winds',
    upright: 'Travel, movement, progress, communication, transition',
    reversed: 'Delays, stagnation, lack of progress, miscommunication',
    image: '/cards/Six_of_Winds.webp',
  },
  {
    id: 'ca-70',
    name: 'Seven of Winds',
    upright: 'Deception, betrayal, theft, cunning, strategy',
    reversed: 'Honesty, truth, clarity, straightforwardness',
    image: '/cards/Seven_of_Winds.webp',
  },
  {
    id: 'ca-71',
    name: 'Eight of Winds',
    upright: 'Restriction, limitation, confinement, powerlessness, struggle',
    reversed: 'Freedom, liberation, release, empowerment',
    image: '/cards/Eight_of_Winds.webp',
  },
  {
    id: 'ca-72',
    name: 'Nine of Winds',
    upright: 'Anxiety, worry, fear, nightmares, despair',
    reversed: 'Hope, relief, clarity, peace, recovery',
    image: '/cards/Nine_of_Winds.webp',
  },
  {
    id: 'ca-73',
    name: 'Ten of Winds',
    upright: 'Betrayal, loss, pain, ruin, ending',
    reversed: 'Recovery, healing, new beginning, hope',
    image: '/cards/Ten_of_Winds.webp',
  },
  {
    id: 'ca-74',
    name: 'Page of Winds',
    upright: 'Curiosity, communication, learning, new ideas, exploration',
    reversed: 'Lack of curiosity, lack of communication, immaturity',
    image: '/cards/Page_of_Winds.webp',
  },
  {
    id: 'ca-75',
    name: 'Knight of Winds',
    upright: 'Action, impulsiveness, haste, bravery, adventure',
    reversed: 'Recklessness, lack of direction, aggression, impatience',
    image: '/cards/Knight_of_Winds.webp',
  },
  {
    id: 'ca-76',
    name: 'Queen of Winds',
    upright: 'Clarity, communication, intelligence, independence, honesty',
    reversed: 'Confusion, lack of clarity, lack of communication',
    image: '/cards/Queen_of_Winds.webp',
  },
  {
    id: 'ca-77',
    name: 'King of Winds',
    upright: 'Authority, leadership, intellectual power, truth, justice',
    reversed: 'Lack of authority, lack of leadership, dishonesty',
    image: '/cards/King_of_Winds.webp',
  },
];
